name: customizedControl
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required:  false
        type:  choice
        options:
          - dev
          - pre
      browser:
        description:  "select browser type"
        required:  true
        type:  checkboxes
        options:
          - chrome
          - edge
          - firefox
      test_type:
        description:  "Select Test Type"
        required:  true
        type:  choice
        options:
          - Regression
          - Sanity
      custom_type:
        description:  "Enter custom value"
        required:  true
        type:  string
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      -  name: oneline statement
         run: echo Hello word updated
